### ISSUE TITLE
 How to generate the similarity matrices？

### ISSUE THREAD

**Issue by hewumars** [UDLF/UDLF#1]
I found that the similarity in the Soccer dataset is not a float between 0 and 1, but an integer. How to generate the similarity matrices？

**Comment by lucasPV** [comment]
Thank you for the contact!

You can generate a similarity matrix by doing the following:
- Find the maximum element in the matrix;
- Divide all the elements by the max element.

After these steps, all elements should be in the interval [0,1].

If you have any other issue, feel free to contact us again.

**Comment by hewumars** [comment]
Thank you for your reply! I have modified the INPUT_FILE_FORMAT parameters from MATRIX to RK.  In this format, it is easier for me to generate a ranking list for testing.
